### ISSUE TITLE
Least Squares todo

### ISSUE THREAD

**Issue by hokiespurs** [hokiespurs/learnbook#1]
### Main Sections
- [ ] Basic Statistics
- [ ] RANSAC
- [ ] covariance/ellipse/confidence intervals
- [ ] TPU -GLOPOV/SLOPOV (fish tank, distance between two points)
- [x] Derivations
- [x] Variables

### Summary Sections
- [x] OLS (ax^2+bx+c = y)
- [x] WLS (same as OLS, but weighted)
- [x] GLS  (2D conformal)
- [x] Nonlinear (amplitude and phase of sin wave)
- [x] TLS (y = mx + b... compare to GLS)

### Geomatics Examples
- [ ] TPU y = mx + b
- [ ] RANSAC plane fitting
- [ ] 3D conformal
- [ ] Space Resection
- [ ] TPU Space Resection -> Ortho DSM
- [ ] Space Intersection
- [ ] mini-SfM 
###
