### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hokiespurs** [hokiespurs/learnbook#5]
- [ ] finish draft of least squares
  - [ ] move error theory to another chapter
  - [ ] introduce lsr.m and examples
- [x] move algorithms to general-purpose-matlab
  - [x] ransac
  - [x] lsr
  - [x] calcErrorProp
